project:
  type: book
  output-dir: docs

book:
  title: "Introduction to GPUs and CUDA programming"
  author: "RA Stringer"
  repo-url: "https://github.com/rastringer/gpu_cuda_book"
  cover-image: "images/logo.png"
  chapters:
    - index.qmd
    - gpu_architecture.ipynb
    - c_to_cuda.ipynb
    - python_cuda.ipynb
    - nsight_attention.ipynb
    - summary.qmd
    # - references.qmd

# bibliography: references.bib

format:
  html:
    theme: sandstone
    fontsize: 1.1em
  pdf:
    documentclass: scrreprt



